import {
  GiAcorn,
  GiAlienSkull,
  GiAlienStare,
  GiAndroidMask,
  GiAnimalSkull,
  GiArmoredBoomerang,
  GiArrowCluster,
  GiArrowsShield,
  GiArtificialHive,
  GiArtificialIntelligence,
  GiAura,
  GiAxeSword,
  GiBackpack,
  GiBarbarian,
  GiBatwingEmblem,
  GiBattleGear,
  GiBeamSatellite,
  GiBearHead,
  GiBlackKnightHelm,
  GiBoltShield,
  GiBoneKnife,
  GiBulletImpacts,
  GiBurningEye,
  GiButterfly,
  GiCactus,
  GiCampfire,
  GiCannon,
  GiCardRandom,
  GiCat,
  GiChessKing,
  GiClover,
  GiCometSpark,
  GiCrossbow,
  GiCrossedAxes,
  GiCrossedPistols,
  GiCrossedSabres,
  GiCrystalBars,
  GiCyberEye,
  GiCyborgFace,
  GiDeer,
  GiDiamondRing,
  GiDogHouse,
  GiDoubleDragon,
  GiDragonBreath,
  GiEagleHead,
  GiElephant,
  GiEnergyArrow,
  GiEnergyBreath,
  GiEnergySword,
  GiEyeShield,
  GiFairy,
  GiFireShield,
  GiFlail,
  GiFlowerPot,
  GiFlyingDagger,
  GiFoxHead,
  GiFrog,
  GiGauntlet,
  GiGhostAlly,
  GiGoblinHead,
  GiGoldStack,
  GiGolemHead,
  GiGrab,
  GiGriffinSymbol,
  GiGrimReaper,
  GiHalberd,
  GiHandcuffs,
  GiHorseHead,
  GiHummingbird,
  GiJetpack,
  GiKeyCard,
  GiKrakenTentacle,
  GiLantern,
  GiLeafSwirl,
  GiLighthouse,
  GiLightningArc,
  GiLightningBow,
  GiLightningHelix,
  GiLightningShield,
  GiLion,
  GiLockedChest,
  GiMaceHead,
  GiMaskedSpider,
  GiMeeple,
  GiMightyForce,
  GiMinotaur,
  GiMountains,
  GiMushroom,
  GiOak,
  GiOpenTreasureChest,
  GiOwl,
  GiPanda,
  GiPineTree,
  GiPokerHand,
  GiPotionOfMadness,
  GiPunchBlast,
  GiRabbit,
  GiRat,
  GiRayGun,
  GiRobotAntennas,
  GiRocketFlight,
  GiRollingDices,
  GiScythe,
  GiSharkFin,
  GiShieldBash,
  GiShieldEchoes,
  GiShotgun,
  GiSnake,
  GiSnowman,
  GiSpaceship,
  GiSpearHook,
  GiSpikedShield,
  GiStarGate,
  GiStopwatch,
  GiSwordBrandish,
  GiSwordWound,
  GiThorHammer,
  GiTomahawk,
  GiTornado,
  GiTrident,
  GiTrophyCup,
  GiTurtle,
  GiUnicorn,
  GiVampireDracula,
  GiVikingHead,
  GiVolcano,
  GiVortex,
  GiWarlockEye,
  GiWaterDrop,
  GiWaves,
  GiWhaleTail,
  GiWolfHead,
  GiWolfHowl,
  GiWyvern,
} from "react-icons/gi";
import { IconDef } from "../domain";

const ADDITIONAL_ICONS: IconDef[] = [
  { name: "Alien", component: GiAlienStare, key: "alienstare", category: "superheroes" },
  { name: "Android mask", component: GiAndroidMask, key: "androidmask", category: "superheroes" },
  { name: "Boomerang", component: GiArmoredBoomerang, key: "boomerang", category: "superheroes" },
  { name: "Artificial intelligence", component: GiArtificialIntelligence, key: "ai", category: "superheroes" },
  { name: "Aura", component: GiAura, key: "aura", category: "superheroes" },
  { name: "Bat emblem", component: GiBatwingEmblem, key: "batemblem", category: "superheroes" },
  { name: "Bolt shield", component: GiBoltShield, key: "boltshield", category: "superheroes" },
  { name: "Burning eye", component: GiBurningEye, key: "burningeye", category: "superheroes" },
  { name: "Cyber eye", component: GiCyberEye, key: "cybereye", category: "superheroes" },
  { name: "Energy arrow", component: GiEnergyArrow, key: "energyarrow", category: "superheroes" },
  { name: "Energy breath", component: GiEnergyBreath, key: "energybreath", category: "superheroes" },
  { name: "Eye shield", component: GiEyeShield, key: "eyeshield", category: "superheroes" },
  { name: "Fire shield", component: GiFireShield, key: "fireshield", category: "superheroes" },
  { name: "Gauntlet", component: GiGauntlet, key: "gauntlet", category: "superheroes" },
  { name: "Grab", component: GiGrab, key: "grab", category: "superheroes" },
  { name: "Handcuffs", component: GiHandcuffs, key: "handcuffs", category: "superheroes" },
  { name: "Lightning arc", component: GiLightningArc, key: "lightningarc", category: "superheroes" },
  { name: "Lightning bow", component: GiLightningBow, key: "lightningbow", category: "superheroes" },
  { name: "Lightning helix", component: GiLightningHelix, key: "lightninghelix", category: "superheroes" },
  { name: "Lightning shield", component: GiLightningShield, key: "lightningshield", category: "superheroes" },
  { name: "Masked spider", component: GiMaskedSpider, key: "maskedspider", category: "superheroes" },
  { name: "Mighty force", component: GiMightyForce, key: "mightyforce", category: "superheroes" },
  { name: "Shield echo", component: GiShieldEchoes, key: "shieldecho", category: "superheroes" },
  { name: "Thor hammer", component: GiThorHammer, key: "thorhammer", category: "superheroes" },
  { name: "Vortex", component: GiVortex, key: "vortex", category: "superheroes" },

  { name: "Black knight", component: GiBlackKnightHelm, key: "blackknight", category: "fantasy" },
  { name: "Double dragon", component: GiDoubleDragon, key: "doubledragon", category: "fantasy" },
  { name: "Dragon breath", component: GiDragonBreath, key: "dragonbreath", category: "fantasy" },
  { name: "Fairy", component: GiFairy, key: "fairy", category: "fantasy" },
  { name: "Ghost ally", component: GiGhostAlly, key: "ghostally", category: "fantasy" },
  { name: "Goblin", component: GiGoblinHead, key: "goblin", category: "fantasy" },
  { name: "Golem", component: GiGolemHead, key: "golem", category: "fantasy" },
  { name: "Griffin", component: GiGriffinSymbol, key: "griffin", category: "fantasy" },
  { name: "Grim reaper", component: GiGrimReaper, key: "grimreaper", category: "fantasy" },
  { name: "Kraken", component: GiKrakenTentacle, key: "kraken", category: "fantasy" },
  { name: "Minotaur", component: GiMinotaur, key: "minotaur", category: "fantasy" },
  { name: "Unicorn", component: GiUnicorn, key: "unicorn", category: "fantasy" },
  { name: "Vampire lord", component: GiVampireDracula, key: "vampirelord", category: "fantasy" },
  { name: "Viking", component: GiVikingHead, key: "viking", category: "fantasy" },
  { name: "Warlock", component: GiWarlockEye, key: "warlock", category: "fantasy" },
  { name: "Wolf", component: GiWolfHead, key: "wolf", category: "fantasy" },
  { name: "Wyvern", component: GiWyvern, key: "wyvern", category: "fantasy" },

  { name: "Arrow cluster", component: GiArrowCluster, key: "arrowcluster", category: "combat" },
  { name: "Arrow shield", component: GiArrowsShield, key: "arrowshield", category: "combat" },
  { name: "Axe sword", component: GiAxeSword, key: "axesword", category: "combat" },
  { name: "Barbarian", component: GiBarbarian, key: "barbarian", category: "combat" },
  { name: "Battle gear", component: GiBattleGear, key: "battlegear", category: "combat" },
  { name: "Bone knife", component: GiBoneKnife, key: "boneknife", category: "combat" },
  { name: "Bullet impacts", component: GiBulletImpacts, key: "bulletimpacts", category: "combat" },
  { name: "Cannon", component: GiCannon, key: "cannon", category: "combat" },
  { name: "Crossbow", component: GiCrossbow, key: "crossbow", category: "combat" },
  { name: "Crossed axes", component: GiCrossedAxes, key: "crossedaxes", category: "combat" },
  { name: "Crossed pistols", component: GiCrossedPistols, key: "crossedpistols", category: "combat" },
  { name: "Crossed sabres", component: GiCrossedSabres, key: "crossedsabres", category: "combat" },
  { name: "Energy sword", component: GiEnergySword, key: "energysword", category: "combat" },
  { name: "Flail", component: GiFlail, key: "flail", category: "combat" },
  { name: "Flying dagger", component: GiFlyingDagger, key: "flyingdagger", category: "combat" },
  { name: "Halberd", component: GiHalberd, key: "halberd", category: "combat" },
  { name: "Mace", component: GiMaceHead, key: "mace", category: "combat" },
  { name: "Punch blast", component: GiPunchBlast, key: "punchblast", category: "combat" },
  { name: "Scythe", component: GiScythe, key: "scythe", category: "combat" },
  { name: "Shield bash", component: GiShieldBash, key: "shieldbash", category: "combat" },
  { name: "Shotgun", component: GiShotgun, key: "shotgun", category: "combat" },
  { name: "Spear hook", component: GiSpearHook, key: "spearhook", category: "combat" },
  { name: "Spiked shield", component: GiSpikedShield, key: "spikedshield", category: "combat" },
  { name: "Sword brandish", component: GiSwordBrandish, key: "swordbrandish", category: "combat" },
  { name: "Sword wound", component: GiSwordWound, key: "swordwound", category: "combat" },
  { name: "Tomahawk", component: GiTomahawk, key: "tomahawk", category: "combat" },
  { name: "Trident", component: GiTrident, key: "trident", category: "combat" },

  { name: "Animal skull", component: GiAnimalSkull, key: "animalskull", category: "nature" },
  { name: "Bear", component: GiBearHead, key: "bear", category: "nature" },
  { name: "Butterfly", component: GiButterfly, key: "butterfly", category: "nature" },
  { name: "Cactus", component: GiCactus, key: "cactus", category: "nature" },
  { name: "Campfire", component: GiCampfire, key: "campfire", category: "nature" },
  { name: "Cat profile", component: GiCat, key: "catprofile", category: "nature" },
  { name: "Clover", component: GiClover, key: "clover", category: "nature" },
  { name: "Deer", component: GiDeer, key: "deer", category: "nature" },
  { name: "Dog house", component: GiDogHouse, key: "doghouse", category: "nature" },
  { name: "Eagle", component: GiEagleHead, key: "eagle", category: "nature" },
  { name: "Elephant", component: GiElephant, key: "elephant", category: "nature" },
  { name: "Flower", component: GiFlowerPot, key: "flower", category: "nature" },
  { name: "Fox", component: GiFoxHead, key: "fox", category: "nature" },
  { name: "Frog", component: GiFrog, key: "frog", category: "nature" },
  { name: "Horse head", component: GiHorseHead, key: "horsehead", category: "nature" },
  { name: "Hummingbird", component: GiHummingbird, key: "hummingbird", category: "nature" },
  { name: "Leaf swirl", component: GiLeafSwirl, key: "leafswirl", category: "nature" },
  { name: "Lion", component: GiLion, key: "lion", category: "nature" },
  { name: "Mountains", component: GiMountains, key: "mountains", category: "nature" },
  { name: "Mushroom", component: GiMushroom, key: "mushroom", category: "nature" },
  { name: "Oak", component: GiOak, key: "oak", category: "nature" },
  { name: "Owl", component: GiOwl, key: "owl", category: "nature" },
  { name: "Panda", component: GiPanda, key: "panda", category: "nature" },
  { name: "Pine tree", component: GiPineTree, key: "pinetree", category: "nature" },
  { name: "Rabbit", component: GiRabbit, key: "rabbit", category: "nature" },
  { name: "Rat", component: GiRat, key: "rat", category: "nature" },
  { name: "Shark", component: GiSharkFin, key: "shark", category: "nature" },
  { name: "Snake", component: GiSnake, key: "snake", category: "nature" },
  { name: "Snowman", component: GiSnowman, key: "snowman", category: "nature" },
  { name: "Tornado", component: GiTornado, key: "tornado", category: "nature" },
  { name: "Turtle", component: GiTurtle, key: "turtle", category: "nature" },
  { name: "Volcano", component: GiVolcano, key: "volcano", category: "nature" },
  { name: "Water drop", component: GiWaterDrop, key: "waterdrop", category: "nature" },
  { name: "Waves", component: GiWaves, key: "waves", category: "nature" },
  { name: "Whale", component: GiWhaleTail, key: "whale", category: "nature" },
  { name: "Wolf howl", component: GiWolfHowl, key: "wolfhowl", category: "nature" },

  { name: "Alien skull", component: GiAlienSkull, key: "alienskull", category: "scifi" },
  { name: "Artificial hive", component: GiArtificialHive, key: "artificialhive", category: "scifi" },
  { name: "Beam satellite", component: GiBeamSatellite, key: "beamsatellite", category: "scifi" },
  { name: "Comet", component: GiCometSpark, key: "comet", category: "scifi" },
  { name: "Cyborg", component: GiCyborgFace, key: "cyborg", category: "scifi" },
  { name: "Jetpack", component: GiJetpack, key: "jetpack", category: "scifi" },
  { name: "Ray gun", component: GiRayGun, key: "raygun", category: "scifi" },
  { name: "Robot antennas", component: GiRobotAntennas, key: "robotantennas", category: "scifi" },
  { name: "Rocket flight", component: GiRocketFlight, key: "rocketflight", category: "scifi" },
  { name: "Spaceship", component: GiSpaceship, key: "spaceship", category: "scifi" },
  { name: "Star gate", component: GiStarGate, key: "stargate", category: "scifi" },

  { name: "Acorn", component: GiAcorn, key: "acorn", category: "objects" },
  { name: "Backpack", component: GiBackpack, key: "backpack", category: "objects" },
  { name: "Random card", component: GiCardRandom, key: "randomcard", category: "objects" },
  { name: "Chess king", component: GiChessKing, key: "chessking", category: "objects" },
  { name: "Crystal bars", component: GiCrystalBars, key: "crystalbars", category: "objects" },
  { name: "Diamond ring", component: GiDiamondRing, key: "diamondring", category: "objects" },
  { name: "Gold stack", component: GiGoldStack, key: "goldstack", category: "objects" },
  { name: "Key card", component: GiKeyCard, key: "keycard", category: "objects" },
  { name: "Lantern", component: GiLantern, key: "lantern", category: "objects" },
  { name: "Lighthouse", component: GiLighthouse, key: "lighthouse", category: "objects" },
  { name: "Locked chest", component: GiLockedChest, key: "lockedchest", category: "objects" },
  { name: "Meeple", component: GiMeeple, key: "meeple", category: "objects" },
  { name: "Treasure chest", component: GiOpenTreasureChest, key: "treasurechest", category: "objects" },
  { name: "Poker hand", component: GiPokerHand, key: "pokerhand", category: "objects" },
  { name: "Madness potion", component: GiPotionOfMadness, key: "madnesspotion", category: "objects" },
  { name: "Rolling dice", component: GiRollingDices, key: "rollingdice", category: "objects" },
  { name: "Stopwatch", component: GiStopwatch, key: "stopwatch", category: "objects" },
  { name: "Trophy cup", component: GiTrophyCup, key: "trophycup", category: "objects" },
];

export { ADDITIONAL_ICONS };
