import {
  FaHeart,
  FaStar,
  FaCrown,
  FaFire,
  FaGem,
  FaSkull,
  FaMagic,
  FaSun,
  FaMoon,
  FaCompass,
  FaBook,
  FaWrench,
  FaAppleAlt,
  FaBolt,
  FaCoins,
  FaSpider,
  FaDna,
  FaBalanceScale,
  FaChess,
  FaChessKnight,
  FaChessRook,
  FaChessQueen,
  FaDiceD20,
  FaDice,
  FaCrosshairs,
  FaArrowUp,
  FaArrowDown,
  FaHammer,
  FaFlask,
  FaCog,
  FaKey,
  FaLock,
  FaUnlock,
  FaMap,
  FaMapMarkedAlt,
  FaHourglass,
  FaFeather,
  FaPaw,
  FaFish,
  FaIcicles,
  FaCloud,
  FaCloudRain,
  FaGlobe,
  FaCross,
  FaSkullCrossbones,
  FaCampground,
  FaMountain,
  FaTree,
  FaLeaf,
  FaSeedling,
  FaTractor,
  FaUserSecret,
  FaUserNinja,
  FaDragon,
  FaDungeon,
  FaHatWizard,
  FaScroll,
  FaRing,
  FaGhost,
  FaMeteor,
  FaRadiation,
  FaBiohazard,
  FaBug,
  FaVirus,
  FaRobot,
  FaRocket,
  FaSatellite,
  FaSatelliteDish,
  FaFortAwesome,
  FaChessBishop,
  FaChessPawn,
  FaDiceSix,
  FaDiceThree,
  FaDiceFive,
  FaHandPointUp,
  FaHandshake,
  FaAnchor,
  FaShip,
  FaWind,
  FaCloudShowersHeavy,
  FaCloudSun,
  FaCloudMoon,
  FaSnowflake,
  FaTemperatureHigh,
} from "react-icons/fa";
import {
  FaBurst,
  FaDroplet,
  FaHandBackFist,
  FaHandFist,
  FaHelmetSafety,
  FaMask,
  FaPeopleGroup,
  FaShieldHalved,
  FaShieldHeart,
  FaTowerBroadcast,
  FaTowerCell,
  FaWandMagicSparkles,
  FaWheatAwn,
} from "react-icons/fa6";
import { GiPocketBow } from "react-icons/gi";

import { PiWarningFill } from "react-icons/pi";
import { RiSwordFill } from "react-icons/ri";
import { IconDef } from "../domain";

const ICONS: IconDef[] = [
  { name: "Heart", component: FaHeart, key: "heart" },
  { name: "Warning", component: PiWarningFill, key: "warning" },
  { name: "Star", component: FaStar, key: "star" },
  { name: "Shield", component: FaShieldHalved, key: "shield" },

  { name: "Sun", component: FaSun, key: "sun" },
  { name: "Water", component: FaDroplet, key: "water" },
  { name: "Skull", component: FaSkull, key: "skull" },
  { name: "Fire", component: FaFire, key: "fire" },
  { name: "Leaf", component: FaLeaf, key: "leaf" },

  { name: "Crown", component: FaCrown, key: "crown" },
  { name: "Bolt", component: FaBolt, key: "bolt" },
  { name: "Gem", component: FaGem, key: "gem" },
  { name: "Coins", component: FaCoins, key: "coins" },
  { name: "Magic", component: FaMagic, key: "magic" },
  { name: "Compass", component: FaCompass, key: "compass" },
  { name: "Apple", component: FaAppleAlt, key: "applealt" },
  { name: "Book", component: FaBook, key: "book" },
  { name: "Wrench", component: FaWrench, key: "wrench" },

  { name: "Spider", component: FaSpider, key: "spider" },
  { name: "Dna", component: FaDna, key: "dna" },
  { name: "Mask", component: FaMask, key: "mask" },
  { name: "Justice", component: FaBalanceScale, key: "justice" },
  { name: "Leadership", component: FaPeopleGroup, key: "leadership" },
  { name: "Aggression", component: FaHandBackFist, key: "aggression" },
  { name: "Protection", component: FaShieldHeart, key: "protection" },

  { name: "Moon", component: FaMoon, key: "moon" },
  { name: "Burst", component: FaBurst, key: "burst" },

  { name: "Dragon", component: FaDragon, key: "dragon" },
  { name: "Dungeon", component: FaDungeon, key: "dungeon" },
  { name: "Wizard", component: FaHatWizard, key: "wizard" },
  { name: "Ring", component: FaRing, key: "ring" },
  { name: "Scroll", component: FaScroll, key: "scroll" },
  { name: "Chess", component: FaChess, key: "chess" },
  { name: "Knight", component: FaChessKnight, key: "knight" },
  { name: "Rook", component: FaChessRook, key: "rook" },
  { name: "Queen", component: FaChessQueen, key: "queen" },
  { name: "Dice D20", component: FaDiceD20, key: "d20" },
  { name: "Dice", component: FaDice, key: "dice" },
  { name: "Sword", component: RiSwordFill, key: "sword" },
  { name: "Target", component: FaCrosshairs, key: "target" },
  { name: "Arrow Up", component: FaArrowUp, key: "arrowup" },
  { name: "Arrow Down", component: FaArrowDown, key: "arrowdown" },
  { name: "Mountain", component: FaMountain, key: "mountain" },
  { name: "Camp", component: FaCampground, key: "camp" },
  { name: "Anchor", component: FaAnchor, key: "anchor" },
  { name: "Ship", component: FaShip, key: "ship" },
  { name: "Helmet", component: FaHelmetSafety, key: "helmet" },
  { name: "Hammer", component: FaHammer, key: "hammer" },
  { name: "Flask", component: FaFlask, key: "flask" },
  { name: "Cog", component: FaCog, key: "cog" },
  { name: "Key", component: FaKey, key: "key" },
  { name: "Lock", component: FaLock, key: "lock" },
  { name: "Unlock", component: FaUnlock, key: "unlock" },
  { name: "Map", component: FaMap, key: "map" },
  { name: "Marked Map", component: FaMapMarkedAlt, key: "mapmarked" },
  { name: "Hourglass", component: FaHourglass, key: "hourglass" },
  { name: "Tree", component: FaTree, key: "tree" },
  { name: "Feather", component: FaFeather, key: "feather" },
  { name: "Paw", component: FaPaw, key: "paw" },
  { name: "Fish", component: FaFish, key: "fish" },
  { name: "Snowflake", component: FaSnowflake, key: "snowflake" },
  { name: "Icicles", component: FaIcicles, key: "icicles" },
  { name: "Cloud", component: FaCloud, key: "cloud" },
  { name: "Rain", component: FaCloudRain, key: "rain" },
  { name: "Wind", component: FaWind, key: "wind" },
  { name: "Globe", component: FaGlobe, key: "globe" },
  { name: "Rocket", component: FaRocket, key: "rocket" },
  { name: "Tower", component: FaTowerCell, key: "tower" },
  { name: "Bow & Arrow", component: GiPocketBow, key: "bowarrow" },
  { name: "Cross", component: FaCross, key: "cross" },
  { name: "Skull Crossbones", component: FaSkullCrossbones, key: "skullcross" },
  { name: "Seedling", component: FaSeedling, key: "seedling" },
  { name: "Tractor", component: FaTractor, key: "tractor" },
  { name: "Wheat", component: FaWheatAwn, key: "wheat" },
  { name: "Secret Agent", component: FaUserSecret, key: "secret" },
  { name: "Ninja", component: FaUserNinja, key: "ninja" },
  { name: "Magic Wand", component: FaWandMagicSparkles, key: "wand" },
  { name: "Ghost", component: FaGhost, key: "ghost" },
  { name: "Meteor", component: FaMeteor, key: "meteor" },
  { name: "Radiation", component: FaRadiation, key: "radiation" },
  { name: "Biohazard", component: FaBiohazard, key: "biohazard" },
  { name: "Bug", component: FaBug, key: "bug" },
  { name: "Virus", component: FaVirus, key: "virus" },
  { name: "Robot", component: FaRobot, key: "robot" },
  { name: "Satellite", component: FaSatellite, key: "satellite" },
  { name: "Satellite Dish", component: FaSatelliteDish, key: "satdish" },
  {
    name: "Broadcast Tower",
    component: FaTowerBroadcast,
    key: "towerbroadcast",
  },
  { name: "Fortress", component: FaFortAwesome, key: "fort" },
  { name: "Bishop", component: FaChessBishop, key: "bishop" },
  { name: "Pawn", component: FaChessPawn, key: "pawn" },
  { name: "Dice Six", component: FaDiceSix, key: "d6" },
  { name: "Dice Three", component: FaDiceThree, key: "d3" },
  { name: "Dice Five", component: FaDiceFive, key: "d5" },
  { name: "Hand Fist", component: FaHandFist, key: "fist" },
  { name: "Point Up", component: FaHandPointUp, key: "pointup" },
  { name: "Handshake", component: FaHandshake, key: "handshake" },
  { name: "Heavy Rain", component: FaCloudShowersHeavy, key: "rainheavy" },
  { name: "Cloud Sun", component: FaCloudSun, key: "cloudsun" },
  { name: "Cloud Moon", component: FaCloudMoon, key: "cloudmoon" },
  { name: "Temperature High", component: FaTemperatureHigh, key: "temphigh" },
];

const getIconByKey = (key: string) => {
  return ICONS.find((icon) => icon.key === key)?.component || FaHeart;
};

export { ICONS, getIconByKey };
