import { getColorByKey } from "./colors";
import { Layout } from "../domain";

const layoutTemplates: Layout[] = [
  {
    name: "Empty",
    id: "empty",
    counters: [],
  },
  {
    name: "Marvel Champions - 1P",
    id: "marvelSolo",
    counters: [
      {
        id: "villain",
        initialValue: 0,
        name: "Villian",
        backgroundColor: getColorByKey("purple"),
        icon: "skull",
        size: "m",
        xsSpan: 1,
        mdSpan: 1,
        lgSpan: 2,
      },
      {
        id: "threat",
        initialValue: 0,
        name: "Threat",
        backgroundColor: getColorByKey("yellow"),
        icon: "warning",
        size: "m",
        xsSpan: 1,
        mdSpan: 1,
        lgSpan: 2,
      },
      {
        id: "hero",
        initialValue: 0,
        name: "Hero",
        backgroundColor: getColorByKey("red"),
        icon: "heart",
        size: "l",
        xsSpan: 2,
        mdSpan: 2,
        lgSpan: 4,
      },
    ],
  },
  {
    name: "Marvel Champions - 1P+",
    id: "marvelSoloCounters",
    counters: [
      {
        id: "villain",
        initialValue: 0,
        name: "Villain",
        backgroundColor: getColorByKey("purple"),
        icon: "skull",
        size: "s",
      },
      {
        id: "threat",
        initialValue: 0,
        name: "Threat",
        backgroundColor: getColorByKey("yellow"),
        icon: "warning",
        size: "s",
      },
      {
        id: "hero",
        initialValue: 0,
        name: "Hero",
        backgroundColor: getColorByKey("red"),
        icon: "heart",
        size: "m",
      },
      {
        id: "counter",
        initialValue: 0,
        name: "Contador",
        backgroundColor: getColorByKey("black"),
        icon: "star",
        size: "m",
      },
    ],
  },
  {
    name: "Marvel Champions - 2P",
    id: "marvel2P",
    counters: [
      {
        id: "villain",
        initialValue: 0,
        name: "Villain",
        backgroundColor: getColorByKey("purple"),
        icon: "skull",
        size: "s",
      },
      {
        id: "threat",
        initialValue: 0,
        name: "Threat",
        backgroundColor: getColorByKey("yellow"),
        icon: "warning",
        size: "s",
      },
      {
        id: "hero1",
        initialValue: 0,
        name: "Hero 1",
        backgroundColor: getColorByKey("red"),
        icon: "heart",
        size: "m",
      },
      {
        id: "hero2",
        initialValue: 0,
        name: "Hero 2",
        backgroundColor: getColorByKey("blue"),
        icon: "heart",
        size: "m",
      },
    ],
  },
  {
    name: "Marvel Champions - 3P",
    id: "marvel3P",
    counters: [
      {
        id: "villain",
        initialValue: 0,
        name: "Villain",
        backgroundColor: getColorByKey("purple"),
        icon: "skull",
        size: "s",
      },
      {
        id: "threat",
        initialValue: 0,
        name: "Threat",
        backgroundColor: getColorByKey("yellow"),
        icon: "warning",
        size: "s",
      },
      {
        id: "hero1",
        initialValue: 0,
        name: "Hero 1",
        backgroundColor: getColorByKey("red"),
        icon: "heart",
        size: "m",
      },
      {
        id: "hero2",
        initialValue: 0,
        name: "Hero 2",
        backgroundColor: getColorByKey("blue"),
        icon: "heart",
        size: "s",
      },
      {
        id: "hero3",
        initialValue: 0,
        name: "Hero 3",
        backgroundColor: getColorByKey("green"),
        icon: "heart",
        size: "s",
      },
    ],
  },
  {
    name: "Marvel Champions - 4P",
    id: "marvel4P",
    counters: [
      {
        id: "villain",
        initialValue: 0,
        name: "Villano",
        backgroundColor: getColorByKey("purple"),
        icon: "skull",
        size: "large2small",
      },
      {
        id: "threat",
        initialValue: 0,
        name: "Amenaza",
        backgroundColor: getColorByKey("yellow"),
        icon: "warning",
        size: "large2small",
      },
      {
        id: "hero1",
        initialValue: 0,
        name: "Héroe 1",
        backgroundColor: getColorByKey("red"),
        icon: "heart",
        size: "small2medium",
      },
      {
        id: "hero2",
        initialValue: 0,
        name: "Héroe 2",
        backgroundColor: getColorByKey("blue"),
        icon: "heart",
        size: "small2medium",
      },
      {
        id: "hero3",
        initialValue: 0,
        name: "Héroe 3",
        backgroundColor: getColorByKey("green"),
        icon: "heart",
        size: "small2medium",
      },
      {
        id: "hero4",
        initialValue: 0,
        name: "Héroe 4",
        backgroundColor: getColorByKey("magenta"),
        icon: "heart",
        size: "small2medium",
      },
    ],
  },
  {
    name: "Commander",
    id: "commander",
    counters: [
      {
        id: "player1",
        initialValue: 40,
        name: "Ajani",
        backgroundColor: getColorByKey("yellow"),
        icon: "sun",
        size: "large2small",
      },
      {
        id: "player2",
        initialValue: 40,
        name: "Jace",
        backgroundColor: getColorByKey("blue"),
        icon: "water",
        size: "large2small",
      },
      {
        id: "player3",
        initialValue: 40,
        name: "Liliana",
        backgroundColor: getColorByKey("black"),
        icon: "skull",
        size: "large2small",
      },
      {
        id: "player4",
        initialValue: 40,
        name: "Chandra",
        backgroundColor: getColorByKey("orange"),
        icon: "fire",
        size: "large2small",
      },
    ],
  },
  {
    name: "Duelo",
    id: "duel",
    counters: [
      {
        id: "player1",
        initialValue: 20,
        name: "Ajani",
        backgroundColor: getColorByKey("yellow"),
        icon: "sun",
        size: "large",
      },
      {
        id: "player2",
        initialValue: 20,
        name: "Jace",
        backgroundColor: getColorByKey("blue"),
        icon: "water",
        size: "large",
      },
    ],
  },
  {
    name: "Vida/Energía",
    id: "lifeEnergy",
    counters: [
      {
        id: "player1-life",
        initialValue: 20,
        name: "Jugador 1 - Vida",
        backgroundColor: getColorByKey("blue"),
        icon: "heart",
        size: "large2small",
      },
      {
        id: "player1-energy",
        initialValue: 0,
        name: "Jugador 1 - Energía",
        backgroundColor: getColorByKey("yellow"),
        icon: "bolt",
        size: "large2small",
      },
      {
        id: "player2-life",
        initialValue: 20,
        name: "Jugador 2 - Vida",
        backgroundColor: getColorByKey("green"),
        icon: "heart",
        size: "large2small",
      },
      {
        id: "player2-energy",
        initialValue: 0,
        name: "Jugador 2 - Energía",
        backgroundColor: getColorByKey("yellow"),
        icon: "bolt",
        size: "large2small",
      },
    ],
  },
  {
    name: "3 Jugadores",
    id: "life3",
    counters: [
      {
        id: "player1",
        initialValue: 20,
        name: "Jugador 1",
        backgroundColor: getColorByKey("red"),
        icon: "heart",
        size: "full",
      },
      {
        id: "player2",
        initialValue: 20,
        name: "Jugador 2",
        backgroundColor: getColorByKey("blue"),
        icon: "heart",
        size: "large",
      },
      {
        id: "player3",
        initialValue: 20,
        name: "Jugador 3",
        backgroundColor: getColorByKey("green"),
        icon: "heart",
        size: "large",
      },
    ],
  },
  {
    name: "4 Jugadores",
    id: "life4",
    counters: [
      {
        id: "player1",
        initialValue: 20,
        name: "Jugador 1",
        backgroundColor: getColorByKey("yellow"),
        icon: "heart",
        size: "large2small",
      },
      {
        id: "player2",
        initialValue: 20,
        name: "Jugador 2",
        backgroundColor: getColorByKey("blue"),
        icon: "heart",
        size: "large2small",
      },
      {
        id: "player3",
        initialValue: 20,
        name: "Jugador 3",
        backgroundColor: getColorByKey("green"),
        icon: "heart",
        size: "large2small",
      },
      {
        id: "player4",
        initialValue: 20,
        name: "Jugador 4",
        backgroundColor: getColorByKey("purple"),
        icon: "heart",
        size: "large2small",
      },
    ],
  },
  {
    name: "5 Jugadores",
    id: "life5",
    counters: [
      {
        id: "player1",
        initialValue: 20,
        name: "Jugador 1",
        backgroundColor: getColorByKey("red"),
        icon: "heart",
        size: "full",
      },
      {
        id: "player2",
        initialValue: 20,
        name: "Jugador 2",
        backgroundColor: getColorByKey("yellow"),
        icon: "heart",
        size: "large2small",
      },
      {
        id: "player3",
        initialValue: 20,
        name: "Jugador 3",
        backgroundColor: getColorByKey("blue"),
        icon: "heart",
        size: "large2small",
      },
      {
        id: "player4",
        initialValue: 20,
        name: "Jugador 4",
        backgroundColor: getColorByKey("green"),
        icon: "heart",
        size: "large2small",
      },
      {
        id: "player5",
        initialValue: 20,
        name: "Jugador 5",
        backgroundColor: getColorByKey("purple"),
        icon: "heart",
        size: "large2small",
      },
    ],
  },
  {
    name: "6 Jugadores",
    id: "life6",
    counters: [
      {
        id: "player1",
        initialValue: 20,
        name: "Jugador 1",
        backgroundColor: getColorByKey("red"),
        icon: "heart",
        size: "large2small",
      },
      {
        id: "player2",
        initialValue: 20,
        name: "Jugador 2",
        backgroundColor: getColorByKey("blue"),
        icon: "heart",
        size: "large2small",
      },
      {
        id: "player3",
        initialValue: 20,
        name: "Jugador 3",
        backgroundColor: getColorByKey("green"),
        icon: "heart",
        size: "large2small",
      },
      {
        id: "player4",
        initialValue: 20,
        name: "Jugador 4",
        backgroundColor: getColorByKey("yellow"),
        icon: "heart",
        size: "large2small",
      },
      {
        id: "player5",
        initialValue: 20,
        name: "Jugador 5",
        backgroundColor: getColorByKey("purple"),
        icon: "heart",
        size: "large2small",
      },
      {
        id: "player6",
        initialValue: 20,
        name: "Jugador 6",
        backgroundColor: getColorByKey("orange"),
        icon: "heart",
        size: "large2small",
      },
    ],
  },
];

export { layoutTemplates };
