import { getColorByKey } from "./colors";
import { Layout } from "../domain";
const layoutTemplates: Layout[] = [
  {
    name: "Empty",
    id: "empty",
    counters: [],
  },
  {
    name: "1 Jugador",
    id: "marvelSolo",
    counters: [
      {
        id: "villain",
        initialValue: 0,
        name: "Villain",
        backgroundColor: getColorByKey("purple"),
        icon: "skull",
        xsElementsPerRow: 1,
        mdElementsPerRow: 2,
        lgElementsPerRow: 2,
      },
      {
        id: "threat",
        initialValue: 0,
        name: "Threat",
        backgroundColor: getColorByKey("yellow"),
        icon: "warning",
        xsElementsPerRow: 1,
        mdElementsPerRow: 2,
        lgElementsPerRow: 2,
      },
      {
        id: "hero",
        initialValue: 0,
        name: "Hero",
        backgroundColor: getColorByKey("red"),
        icon: "heart",
        xsElementsPerRow: 1,
        mdElementsPerRow: 1,
        lgElementsPerRow: 1,
      },
    ],
  },
  {
    name: "1 Jugador + recurso",
    id: "marvelSoloCounters",
    counters: [
      {
        id: "villain",
        initialValue: 0,
        name: "Villain",
        backgroundColor: getColorByKey("purple"),
        icon: "skull",
        xsElementsPerRow: 2,
        mdElementsPerRow: 2,
        lgElementsPerRow: 2,
      },
      {
        id: "threat",
        initialValue: 0,
        name: "Threat",
        backgroundColor: getColorByKey("yellow"),
        icon: "warning",
        xsElementsPerRow: 2,
        mdElementsPerRow: 2,
        lgElementsPerRow: 2,
      },
      {
        id: "hero",
        initialValue: 0,
        name: "Hero",
        backgroundColor: getColorByKey("red"),
        icon: "heart",
        xsElementsPerRow: 1,
        mdElementsPerRow: 2,
        lgElementsPerRow: 2,
      },
      {
        id: "counter",
        initialValue: 0,
        name: "Resource",
        backgroundColor: getColorByKey("black"),
        icon: "star",
        xsElementsPerRow: 1,
        mdElementsPerRow: 2,
        lgElementsPerRow: 2,
      },
    ],
  },
  {
    name: "2 Jugadores",
    id: "marvel2P",
    counters: [
      {
        id: "villain",
        initialValue: 0,
        name: "Villain",
        backgroundColor: getColorByKey("purple"),
        icon: "skull",
        xsElementsPerRow: 2,
        mdElementsPerRow: 2,
        lgElementsPerRow: 2,
      },
      {
        id: "threat",
        initialValue: 0,
        name: "Threat",
        backgroundColor: getColorByKey("yellow"),
        icon: "warning",
        xsElementsPerRow: 2,
        mdElementsPerRow: 2,
        lgElementsPerRow: 2,
      },
      {
        id: "hero1",
        initialValue: 0,
        name: "Hero 1",
        backgroundColor: getColorByKey("red"),
        icon: "heart",
        xsElementsPerRow: 1,
        mdElementsPerRow: 2,
        lgElementsPerRow: 2,
      },
      {
        id: "hero2",
        initialValue: 0,
        name: "Hero 2",
        backgroundColor: getColorByKey("blue"),
        icon: "heart",
        xsElementsPerRow: 1,
        mdElementsPerRow: 2,
        lgElementsPerRow: 2,
      },
    ],
  },
  {
    name: "3 Jugadores",
    id: "marvel3P",
    counters: [
      {
        id: "villain",
        initialValue: 0,
        name: "Villain",
        backgroundColor: getColorByKey("purple"),
        icon: "skull",
        xsElementsPerRow: 2,
        mdElementsPerRow: 2,
        lgElementsPerRow: 2,
      },
      {
        id: "threat",
        initialValue: 0,
        name: "Threat",
        backgroundColor: getColorByKey("yellow"),
        icon: "warning",
        xsElementsPerRow: 2,
        mdElementsPerRow: 2,
        lgElementsPerRow: 2,
      },
      {
        id: "hero1",
        initialValue: 0,
        name: "Hero 1",
        backgroundColor: getColorByKey("red"),
        icon: "heart",
        xsElementsPerRow: 1,
        mdElementsPerRow: 3,
        lgElementsPerRow: 3,
      },
      {
        id: "hero2",
        initialValue: 0,
        name: "Hero 2",
        backgroundColor: getColorByKey("blue"),
        icon: "heart",
        xsElementsPerRow: 2,
        mdElementsPerRow: 3,
        lgElementsPerRow: 3,
      },
      {
        id: "hero3",
        initialValue: 0,
        name: "Hero 3",
        backgroundColor: getColorByKey("green"),
        icon: "heart",
        xsElementsPerRow: 2,
        mdElementsPerRow: 3,
        lgElementsPerRow: 3,
      },
    ],
  },
  {
    name: "4 Jugadores",
    id: "marvel4P",
    counters: [
      {
        id: "villain",
        initialValue: 0,
        name: "Villain",
        backgroundColor: getColorByKey("purple"),
        icon: "skull",
        xsElementsPerRow: 2,
        mdElementsPerRow: 2,
        lgElementsPerRow: 2,
      },
      {
        id: "threat",
        initialValue: 0,
        name: "Threat",
        backgroundColor: getColorByKey("yellow"),
        icon: "warning",
        xsElementsPerRow: 2,
        mdElementsPerRow: 2,
        lgElementsPerRow: 2,
      },
      {
        id: "hero1",
        initialValue: 0,
        name: "Hero 1",
        backgroundColor: getColorByKey("red"),
        icon: "heart",
        xsElementsPerRow: 2,
        mdElementsPerRow: 2,
        lgElementsPerRow: 4,
      },
      {
        id: "hero2",
        initialValue: 0,
        name: "Hero 2",
        backgroundColor: getColorByKey("blue"),
        icon: "heart",
        xsElementsPerRow: 2,
        mdElementsPerRow: 2,
        lgElementsPerRow: 4,
      },
      {
        id: "hero3",
        initialValue: 0,
        name: "Hero 3",
        backgroundColor: getColorByKey("green"),
        icon: "heart",
        xsElementsPerRow: 2,
        mdElementsPerRow: 2,
        lgElementsPerRow: 4,
      },
      {
        id: "hero4",
        initialValue: 0,
        name: "Hero 4",
        backgroundColor: getColorByKey("magenta"),
        icon: "heart",
        xsElementsPerRow: 2,
        mdElementsPerRow: 2,
        lgElementsPerRow: 4,
      },
    ],
  },
  // Generic: 1 and 2 players (added)
  {
    name: "1 Player",
    id: "life1",
    counters: [
      {
        id: "player1",
        initialValue: 20,
        name: "Player 1",
        backgroundColor: getColorByKey("yellow"),
        icon: "heart",
        xsElementsPerRow: 1,
        mdElementsPerRow: 1,
        lgElementsPerRow: 1,
      },
    ],
  },
  {
    name: "2 Players",
    id: "life2",
    counters: [
      {
        id: "player1",
        initialValue: 20,
        name: "Player 1",
        backgroundColor: getColorByKey("yellow"),
        icon: "heart",
        xsElementsPerRow: 1,
        mdElementsPerRow: 1,
        lgElementsPerRow: 2,
      },
      {
        id: "player2",
        initialValue: 20,
        name: "Player 2",
        backgroundColor: getColorByKey("blue"),
        icon: "heart",
        xsElementsPerRow: 1,
        mdElementsPerRow: 1,
        lgElementsPerRow: 2,
      },
    ],
  },
  {
    name: "Commander",
    id: "commander",
    counters: [
      {
        id: "player1",
        initialValue: 40,
        name: "Ajani",
        backgroundColor: getColorByKey("yellow"),
        icon: "sun",
        xsElementsPerRow: 2,
        mdElementsPerRow: 2,
        lgElementsPerRow: 2,
      },
      {
        id: "player2",
        initialValue: 40,
        name: "Jace",
        backgroundColor: getColorByKey("blue"),
        icon: "water",
        xsElementsPerRow: 2,
        mdElementsPerRow: 2,
        lgElementsPerRow: 2,
      },
      {
        id: "player3",
        initialValue: 40,
        name: "Liliana",
        backgroundColor: getColorByKey("black"),
        icon: "skull",
        xsElementsPerRow: 2,
        mdElementsPerRow: 2,
        lgElementsPerRow: 2,
      },
      {
        id: "player4",
        initialValue: 40,
        name: "Chandra",
        backgroundColor: getColorByKey("orange"),
        icon: "fire",
        xsElementsPerRow: 2,
        mdElementsPerRow: 2,
        lgElementsPerRow: 2,
      },
    ],
  },
  {
    name: "Duel",
    id: "duel",
    counters: [
      {
        id: "player1",
        initialValue: 20,
        name: "Ajani",
        backgroundColor: getColorByKey("yellow"),
        icon: "sun",
        xsElementsPerRow: 1,
        mdElementsPerRow: 1,
        lgElementsPerRow: 2,
      },
      {
        id: "player2",
        initialValue: 20,
        name: "Jace",
        backgroundColor: getColorByKey("blue"),
        icon: "water",
        xsElementsPerRow: 1,
        mdElementsPerRow: 1,
        lgElementsPerRow: 2,
      },
    ],
  },
  {
    name: "3 Players",
    id: "life3",
    counters: [
      {
        id: "player1",
        initialValue: 20,
        name: "Player 1",
        backgroundColor: getColorByKey("yellow"),
        icon: "heart",
        xsElementsPerRow: 1,
        mdElementsPerRow: 3,
        lgElementsPerRow: 3,
      },
      {
        id: "player2",
        initialValue: 20,
        name: "Player 2",
        backgroundColor: getColorByKey("blue"),
        icon: "heart",
        xsElementsPerRow: 1,
        mdElementsPerRow: 3,
        lgElementsPerRow: 3,
      },
      {
        id: "player3",
        initialValue: 20,
        name: "Player 3",
        backgroundColor: getColorByKey("green"),
        icon: "heart",
        xsElementsPerRow: 1,
        mdElementsPerRow: 3,
        lgElementsPerRow: 3,
      },
    ],
  },
  {
    name: "4 Players",
    id: "life4",
    counters: [
      {
        id: "player1",
        initialValue: 20,
        name: "Player 1",
        backgroundColor: getColorByKey("yellow"),
        icon: "heart",
        xsElementsPerRow: 2,
        mdElementsPerRow: 2,
        lgElementsPerRow: 2,
      },
      {
        id: "player2",
        initialValue: 20,
        name: "Player 2",
        backgroundColor: getColorByKey("blue"),
        icon: "heart",
        xsElementsPerRow: 2,
        mdElementsPerRow: 2,
        lgElementsPerRow: 2,
      },
      {
        id: "player3",
        initialValue: 20,
        name: "Player 3",
        backgroundColor: getColorByKey("green"),
        icon: "heart",
        xsElementsPerRow: 2,
        mdElementsPerRow: 2,
        lgElementsPerRow: 2,
      },
      {
        id: "player4",
        initialValue: 20,
        name: "Player 4",
        backgroundColor: getColorByKey("red"),
        icon: "heart",
        xsElementsPerRow: 2,
        mdElementsPerRow: 2,
        lgElementsPerRow: 2,
      },
    ],
  },
  {
    name: "5 Players",
    id: "life5",
    counters: [
      {
        id: "player1",
        initialValue: 20,
        name: "Player 1",
        backgroundColor: getColorByKey("yellow"),
        icon: "heart",
        xsElementsPerRow: 2,
        mdElementsPerRow: 2,
        lgElementsPerRow: 2,
      },
      {
        id: "player2",
        initialValue: 20,
        name: "Player 2",
        backgroundColor: getColorByKey("blue"),
        icon: "heart",
        xsElementsPerRow: 2,
        mdElementsPerRow: 2,
        lgElementsPerRow: 2,
      },
      {
        id: "player3",
        initialValue: 20,
        name: "Player 3",
        backgroundColor: getColorByKey("green"),
        icon: "heart",
        xsElementsPerRow: 1,
        mdElementsPerRow: 3,
        lgElementsPerRow: 3,
      },
      {
        id: "player4",
        initialValue: 20,
        name: "Player 4",
        backgroundColor: getColorByKey("red"),
        icon: "heart",
        xsElementsPerRow: 2,
        mdElementsPerRow: 3,
        lgElementsPerRow: 3,
      },
      {
        id: "player5",
        initialValue: 20,
        name: "Player 5",
        backgroundColor: getColorByKey("purple"),
        icon: "heart",
        xsElementsPerRow: 2,
        mdElementsPerRow: 3,
        lgElementsPerRow: 3,
      },
    ],
  },
  {
    name: "6 Players",
    id: "life6",
    counters: [
      {
        id: "player1",
        initialValue: 20,
        name: "Player 1",
        backgroundColor: getColorByKey("yellow"),
        icon: "heart",
        xsElementsPerRow: 2,
        mdElementsPerRow: 3,
        lgElementsPerRow: 3,
      },
      {
        id: "player2",
        initialValue: 20,
        name: "Player 2",
        backgroundColor: getColorByKey("blue"),
        icon: "heart",
        xsElementsPerRow: 2,
        mdElementsPerRow: 3,
        lgElementsPerRow: 3,
      },
      {
        id: "player3",
        initialValue: 20,
        name: "Player 3",
        backgroundColor: getColorByKey("green"),
        icon: "heart",
        xsElementsPerRow: 2,
        mdElementsPerRow: 3,
        lgElementsPerRow: 3,
      },
      {
        id: "player4",
        initialValue: 20,
        name: "Player 4",
        backgroundColor: getColorByKey("red"),
        icon: "heart",
        xsElementsPerRow: 2,
        mdElementsPerRow: 3,
        lgElementsPerRow: 3,
      },
      {
        id: "player5",
        initialValue: 20,
        name: "Player 5",
        backgroundColor: getColorByKey("purple"),
        icon: "heart",
        xsElementsPerRow: 2,
        mdElementsPerRow: 3,
        lgElementsPerRow: 3,
      },
      {
        id: "player6",
        initialValue: 20,
        name: "Player 6",
        backgroundColor: getColorByKey("orange"),
        icon: "heart",
        xsElementsPerRow: 2,
        mdElementsPerRow: 3,
        lgElementsPerRow: 3,
      },
    ],
  },
  // Aeon's End: 1–4 players
  {
    name: "1 Player",
    id: "aeons1P",
    counters: [
      {
        id: "nemesis",
        initialValue: 60,
        name: "Nemesis",
        backgroundColor: getColorByKey("crimson"),
        icon: "skull",
        xsElementsPerRow: 1,
        mdElementsPerRow: 2,
        lgElementsPerRow: 2,
      },
      {
        id: "city",
        initialValue: 30,
        name: "Gravehold",
        backgroundColor: getColorByKey("sand"),
        icon: "fort",
        xsElementsPerRow: 1,
        mdElementsPerRow: 2,
        lgElementsPerRow: 2,
      },
      {
        id: "player1",
        initialValue: 10,
        name: "Player 1",
        backgroundColor: getColorByKey("yellow"),
        icon: "player1",
        xsElementsPerRow: 1,
        mdElementsPerRow: 1,
        lgElementsPerRow: 1,
      },
    ],
  },
  {
    name: "2 Players",
    id: "aeons2P",
    counters: [
      {
        id: "nemesis",
        initialValue: 60,
        name: "Nemesis",
        backgroundColor: getColorByKey("crimson"),
        icon: "skull",
        xsElementsPerRow: 2,
        mdElementsPerRow: 2,
        lgElementsPerRow: 2,
      },
      {
        id: "city",
        initialValue: 30,
        name: "Gravehold",
        backgroundColor: getColorByKey("sand"),
        icon: "fort",
        xsElementsPerRow: 2,
        mdElementsPerRow: 2,
        lgElementsPerRow: 2,
      },
      {
        id: "player1",
        initialValue: 10,
        name: "Player 1",
        backgroundColor: getColorByKey("yellow"),
        icon: "player1",
        xsElementsPerRow: 1,
        mdElementsPerRow: 1,
        lgElementsPerRow: 1,
      },
      {
        id: "player2",
        initialValue: 10,
        name: "Player 2",
        backgroundColor: getColorByKey("amber"),
        icon: "player2",
        xsElementsPerRow: 1,
        mdElementsPerRow: 1,
        lgElementsPerRow: 1,
      },
    ],
  },
  {
    name: "3 Players",
    id: "aeons3P",
    counters: [
      {
        id: "nemesis",
        initialValue: 60,
        name: "Nemesis",
        backgroundColor: getColorByKey("crimson"),
        icon: "skull",
        xsElementsPerRow: 2,
        mdElementsPerRow: 2,
        lgElementsPerRow: 2,
      },
      {
        id: "city",
        initialValue: 30,
        name: "Gravehold",
        backgroundColor: getColorByKey("sand"),
        icon: "fort",
        xsElementsPerRow: 2,
        mdElementsPerRow: 2,
        lgElementsPerRow: 2,
      },
      {
        id: "player1",
        initialValue: 10,
        name: "Player 1",
        backgroundColor: getColorByKey("yellow"),
        icon: "player1",
        xsElementsPerRow: 1,
        mdElementsPerRow: 1,
        lgElementsPerRow: 1,
      },
      {
        id: "player2",
        initialValue: 10,
        name: "Player 2",
        backgroundColor: getColorByKey("amber"),
        icon: "player2",
        xsElementsPerRow: 2,
        mdElementsPerRow: 2,
        lgElementsPerRow: 2,
      },
      {
        id: "player3",
        initialValue: 10,
        name: "Player 3",
        backgroundColor: getColorByKey("azure"),
        icon: "player3",
        xsElementsPerRow: 2,
        mdElementsPerRow: 2,
        lgElementsPerRow: 2,
      },
    ],
  },
  {
    name: "4 Players",
    id: "aeons4P",
    counters: [
      {
        id: "nemesis",
        initialValue: 60,
        name: "Nemesis",
        backgroundColor: getColorByKey("crimson"),
        icon: "skull",
        xsElementsPerRow: 2,
        mdElementsPerRow: 2,
        lgElementsPerRow: 2,
      },
      {
        id: "city",
        initialValue: 30,
        name: "Gravehold",
        backgroundColor: getColorByKey("sand"),
        icon: "fort",
        xsElementsPerRow: 2,
        mdElementsPerRow: 2,
        lgElementsPerRow: 2,
      },
      {
        id: "player1",
        initialValue: 10,
        name: "Player 1",
        backgroundColor: getColorByKey("yellow"),
        icon: "player1",
        xsElementsPerRow: 2,
        mdElementsPerRow: 2,
        lgElementsPerRow: 2,
      },
      {
        id: "player2",
        initialValue: 10,
        name: "Player 2",
        backgroundColor: getColorByKey("amber"),
        icon: "player2",
        xsElementsPerRow: 2,
        mdElementsPerRow: 2,
        lgElementsPerRow: 2,
      },
      {
        id: "player3",
        initialValue: 10,
        name: "Player 3",
        backgroundColor: getColorByKey("azure"),
        icon: "player3",
        xsElementsPerRow: 2,
        mdElementsPerRow: 2,
        lgElementsPerRow: 2,
      },
      {
        id: "player4",
        initialValue: 10,
        name: "Player 4",
        backgroundColor: getColorByKey("magenta"),
        icon: "player4",
        xsElementsPerRow: 2,
        mdElementsPerRow: 2,
        lgElementsPerRow: 2,
      },
    ],
  },
];

type GameId = "generic" | "aeons" | "marvel" | "magic";

const gameToLayoutIds: Record<GameId, string[]> = {
  // Genérico: packs de 1-6 jugadores
  generic: ["life1", "life2", "life3", "life4", "life5", "life6"],
  // Aeon's End
  aeons: ["aeons1P", "aeons2P", "aeons3P", "aeons4P"],
  // Magic: solo Commander y Duelo
  magic: ["commander", "duel"],
  // Marvel: solo variantes de Marvel
  marvel: [
    "marvelSolo",
    "marvelSoloCounters",
    "marvel2P",
    "marvel3P",
    "marvel4P",
  ],
};

const layoutsById = new Map(layoutTemplates.map((lt) => [lt.id, lt] as const));

const games = (Object.keys(gameToLayoutIds) as GameId[]).map((id) => ({
  id,
  layouts: gameToLayoutIds[id]
    .map((lid) => layoutsById.get(lid))
    .filter((x): x is Layout => Boolean(x)),
}));

const getGameByLayoutId = (layoutId: string): GameId | null => {
  for (const [gid, ids] of Object.entries(gameToLayoutIds) as Array<
    [GameId, string[]]
  >) {
    if (ids.includes(layoutId)) return gid;
  }
  return null;
};

export { layoutTemplates, games, getGameByLayoutId };
