import { getColorByKey } from "./colors";
import { Layout } from "../domain";

const layoutTemplates: Layout[] = [
  {
    name: "Empty",
    id: "empty",
    counters: [],
  },
  {
    name: "Marvel Champions - 1P",
    id: "marvelSolo",
    counters: [
      {
        id: "villain",
        initialValue: 0,
        name: "Villain",
        backgroundColor: getColorByKey("purple"),
        icon: "skull",
        size: "m",
        xsElementsPerRow: 1,
        mdElementsPerRow: 2,
        lgElementsPerRow: 3,
      },
      {
        id: "threat",
        initialValue: 0,
        name: "Threat",
        backgroundColor: getColorByKey("yellow"),
        icon: "warning",
        size: "m",
        xsElementsPerRow: 1,
        mdElementsPerRow: 2,
        lgElementsPerRow: 3,
      },
      {
        id: "hero",
        initialValue: 0,
        name: "Hero",
        backgroundColor: getColorByKey("red"),
        icon: "heart",
        size: "l",
        xsElementsPerRow: 1,
        mdElementsPerRow: 1,
        lgElementsPerRow: 3,
      },
    ],
  },
  {
    name: "Marvel Champions - 1P+",
    id: "marvelSoloCounters",
    counters: [
      {
        id: "villain",
        initialValue: 0,
        name: "Villain",
        backgroundColor: getColorByKey("purple"),
        icon: "skull",
        size: "s",
        xsElementsPerRow: 2,
        mdElementsPerRow: 2,
        lgElementsPerRow: 2,
      },
      {
        id: "threat",
        initialValue: 0,
        name: "Threat",
        backgroundColor: getColorByKey("yellow"),
        icon: "warning",
        size: "s",
        xsElementsPerRow: 2,
        mdElementsPerRow: 2,
        lgElementsPerRow: 2,
      },
      {
        id: "hero",
        initialValue: 0,
        name: "Hero",
        backgroundColor: getColorByKey("red"),
        icon: "heart",
        size: "m",
        xsElementsPerRow: 1,
        mdElementsPerRow: 2,
        lgElementsPerRow: 2,
      },
      {
        id: "counter",
        initialValue: 0,
        name: "Resource",
        backgroundColor: getColorByKey("black"),
        icon: "star",
        size: "m",
        xsElementsPerRow: 1,
        mdElementsPerRow: 2,
        lgElementsPerRow: 2,
      },
    ],
  },
  {
    name: "Marvel Champions - 2P",
    id: "marvel2P",
    counters: [
      {
        id: "villain",
        initialValue: 0,
        name: "Villain",
        backgroundColor: getColorByKey("purple"),
        icon: "skull",
        size: "s",
        xsElementsPerRow: 2,
        mdElementsPerRow: 2,
        lgElementsPerRow: 2,
      },
      {
        id: "threat",
        initialValue: 0,
        name: "Threat",
        backgroundColor: getColorByKey("yellow"),
        icon: "warning",
        size: "s",
        xsElementsPerRow: 2,
        mdElementsPerRow: 2,
        lgElementsPerRow: 2,
      },
      {
        id: "hero1",
        initialValue: 0,
        name: "Hero 1",
        backgroundColor: getColorByKey("red"),
        icon: "heart",
        size: "m",
        xsElementsPerRow: 1,
        mdElementsPerRow: 2,
        lgElementsPerRow: 2,
      },
      {
        id: "hero2",
        initialValue: 0,
        name: "Hero 2",
        backgroundColor: getColorByKey("blue"),
        icon: "heart",
        size: "m",
        xsElementsPerRow: 1,
        mdElementsPerRow: 2,
        lgElementsPerRow: 2,
      },
    ],
  },
  {
    name: "Marvel Champions - 3P",
    id: "marvel3P",
    counters: [
      {
        id: "villain",
        initialValue: 0,
        name: "Villain",
        backgroundColor: getColorByKey("purple"),
        icon: "skull",
        size: "s",
        xsElementsPerRow: 2,
        mdElementsPerRow: 2,
        lgElementsPerRow: 2,
      },
      {
        id: "threat",
        initialValue: 0,
        name: "Threat",
        backgroundColor: getColorByKey("yellow"),
        icon: "warning",
        size: "s",
        xsElementsPerRow: 2,
        mdElementsPerRow: 2,
        lgElementsPerRow: 2,
      },
      {
        id: "hero1",
        initialValue: 0,
        name: "Hero 1",
        backgroundColor: getColorByKey("red"),
        icon: "heart",
        size: "m",
        xsElementsPerRow: 1,
        mdElementsPerRow: 3,
        lgElementsPerRow: 3,
      },
      {
        id: "hero2",
        initialValue: 0,
        name: "Hero 2",
        backgroundColor: getColorByKey("blue"),
        icon: "heart",
        size: "s",
        xsElementsPerRow: 2,
        mdElementsPerRow: 3,
        lgElementsPerRow: 3,
      },
      {
        id: "hero3",
        initialValue: 0,
        name: "Hero 3",
        backgroundColor: getColorByKey("green"),
        icon: "heart",
        size: "s",
        xsElementsPerRow: 2,
        mdElementsPerRow: 3,
        lgElementsPerRow: 3,
      },
    ],
  },
  {
    name: "Marvel Champions - 4P",
    id: "marvel4P",
    counters: [
      {
        id: "villain",
        initialValue: 0,
        name: "Villain",
        backgroundColor: getColorByKey("purple"),
        icon: "skull",
        size: "m",
        xsElementsPerRow: 2,
        mdElementsPerRow: 2,
        lgElementsPerRow: 2,
      },
      {
        id: "threat",
        initialValue: 0,
        name: "Threat",
        backgroundColor: getColorByKey("yellow"),
        icon: "warning",
        size: "m",
        xsElementsPerRow: 2,
        mdElementsPerRow: 2,
        lgElementsPerRow: 2,
      },
      {
        id: "hero1",
        initialValue: 0,
        name: "Hero 1",
        backgroundColor: getColorByKey("red"),
        icon: "heart",
        size: "m",
        xsElementsPerRow: 2,
        mdElementsPerRow: 2,
        lgElementsPerRow: 4,
      },
      {
        id: "hero2",
        initialValue: 0,
        name: "Hero 2",
        backgroundColor: getColorByKey("blue"),
        icon: "heart",
        size: "m",
        xsElementsPerRow: 2,
        mdElementsPerRow: 2,
        lgElementsPerRow: 4,
      },
      {
        id: "hero3",
        initialValue: 0,
        name: "Hero 3",
        backgroundColor: getColorByKey("green"),
        icon: "heart",
        size: "m",
        xsElementsPerRow: 2,
        mdElementsPerRow: 2,
        lgElementsPerRow: 4,
      },
      {
        id: "hero4",
        initialValue: 0,
        name: "Hero 4",
        backgroundColor: getColorByKey("magenta"),
        icon: "heart",
        size: "m",
        xsElementsPerRow: 2,
        mdElementsPerRow: 2,
        lgElementsPerRow: 4,
      },
    ],
  },
  {
    name: "Commander",
    id: "commander",
    counters: [
      {
        id: "player1",
        initialValue: 40,
        name: "Ajani",
        backgroundColor: getColorByKey("yellow"),
        icon: "sun",
        size: "m",
        xsElementsPerRow: 2,
        mdElementsPerRow: 2,
        lgElementsPerRow: 2,
      },
      {
        id: "player2",
        initialValue: 40,
        name: "Jace",
        backgroundColor: getColorByKey("blue"),
        icon: "water",
        size: "m",
        xsElementsPerRow: 2,
        mdElementsPerRow: 2,
        lgElementsPerRow: 2,
      },
      {
        id: "player3",
        initialValue: 40,
        name: "Liliana",
        backgroundColor: getColorByKey("black"),
        icon: "skull",
        size: "m",
        xsElementsPerRow: 2,
        mdElementsPerRow: 2,
        lgElementsPerRow: 2,
      },
      {
        id: "player4",
        initialValue: 40,
        name: "Chandra",
        backgroundColor: getColorByKey("orange"),
        icon: "fire",
        size: "m",
        xsElementsPerRow: 2,
        mdElementsPerRow: 2,
        lgElementsPerRow: 2,
      },
    ],
  },
  {
    name: "Duel",
    id: "duel",
    counters: [
      {
        id: "player1",
        initialValue: 20,
        name: "Ajani",
        backgroundColor: getColorByKey("yellow"),
        icon: "sun",
        size: "l",
        xsElementsPerRow: 2,
        mdElementsPerRow: 2,
        lgElementsPerRow: 2,
      },
      {
        id: "player2",
        initialValue: 20,
        name: "Jace",
        backgroundColor: getColorByKey("blue"),
        icon: "water",
        size: "l",
        xsElementsPerRow: 2,
        mdElementsPerRow: 2,
        lgElementsPerRow: 2,
      },
    ],
  },
  {
    name: "Life/Energy",
    id: "lifeEnergy",
    counters: [
      {
        id: "player1-life",
        initialValue: 20,
        name: "Player 1 - Life",
        backgroundColor: getColorByKey("blue"),
        icon: "heart",
        size: "l",
        xsElementsPerRow: 2,
        mdElementsPerRow: 2,
        lgElementsPerRow: 2,
      },
      {
        id: "player1-energy",
        initialValue: 0,
        name: "Player 1 - Energy",
        backgroundColor: getColorByKey("yellow"),
        icon: "bolt",
        size: "l",
        xsElementsPerRow: 2,
        mdElementsPerRow: 2,
        lgElementsPerRow: 2,
      },
      {
        id: "player2-life",
        initialValue: 20,
        name: "Player 2 - Life",
        backgroundColor: getColorByKey("green"),
        icon: "heart",
        size: "l",
        xsElementsPerRow: 2,
        mdElementsPerRow: 2,
        lgElementsPerRow: 2,
      },
      {
        id: "player2-energy",
        initialValue: 0,
        name: "Player 2 - Energy",
        backgroundColor: getColorByKey("yellow"),
        icon: "bolt",
        size: "l",
        xsElementsPerRow: 2,
        mdElementsPerRow: 2,
        lgElementsPerRow: 2,
      },
    ],
  },
  {
    name: "3 Players",
    id: "life3",
    counters: [
      {
        id: "player1",
        initialValue: 20,
        name: "Player 1",
        backgroundColor: getColorByKey("red"),
        icon: "heart",
        size: "l",
        xsElementsPerRow: 1,
        mdElementsPerRow: 3,
        lgElementsPerRow: 3,
      },
      {
        id: "player2",
        initialValue: 20,
        name: "Player 2",
        backgroundColor: getColorByKey("blue"),
        icon: "heart",
        size: "l",
        xsElementsPerRow: 2,
        mdElementsPerRow: 3,
        lgElementsPerRow: 3,
      },
      {
        id: "player3",
        initialValue: 20,
        name: "Player 3",
        backgroundColor: getColorByKey("green"),
        icon: "heart",
        size: "l",
        xsElementsPerRow: 2,
        mdElementsPerRow: 3,
        lgElementsPerRow: 3,
      },
    ],
  },
  {
    name: "4 Players",
    id: "life4",
    counters: [
      {
        id: "player1",
        initialValue: 20,
        name: "Player 1",
        backgroundColor: getColorByKey("yellow"),
        icon: "heart",
        size: "l",
        xsElementsPerRow: 2,
        mdElementsPerRow: 2,
        lgElementsPerRow: 2,
      },
      {
        id: "player2",
        initialValue: 20,
        name: "Player 2",
        backgroundColor: getColorByKey("blue"),
        icon: "heart",
        size: "l",
        xsElementsPerRow: 2,
        mdElementsPerRow: 2,
        lgElementsPerRow: 2,
      },
      {
        id: "player3",
        initialValue: 20,
        name: "Player 3",
        backgroundColor: getColorByKey("green"),
        icon: "heart",
        size: "l",
        xsElementsPerRow: 2,
        mdElementsPerRow: 2,
        lgElementsPerRow: 2,
      },
      {
        id: "player4",
        initialValue: 20,
        name: "Player 4",
        backgroundColor: getColorByKey("purple"),
        icon: "heart",
        size: "l",
        xsElementsPerRow: 2,
        mdElementsPerRow: 2,
        lgElementsPerRow: 2,
      },
    ],
  },
  {
    name: "5 Players",
    id: "life5",
    counters: [
      {
        id: "player1",
        initialValue: 20,
        name: "Player 1",
        backgroundColor: getColorByKey("red"),
        icon: "heart",
        size: "l",
        xsElementsPerRow: 2,
        mdElementsPerRow: 2,
        lgElementsPerRow: 2,
      },
      {
        id: "player2",
        initialValue: 20,
        name: "Player 2",
        backgroundColor: getColorByKey("yellow"),
        icon: "heart",
        size: "l",
        xsElementsPerRow: 2,
        mdElementsPerRow: 2,
        lgElementsPerRow: 2,
      },
      {
        id: "player3",
        initialValue: 20,
        name: "Player 3",
        backgroundColor: getColorByKey("blue"),
        icon: "heart",
        size: "l",
        xsElementsPerRow: 1,
        mdElementsPerRow: 3,
        lgElementsPerRow: 3,
      },
      {
        id: "player4",
        initialValue: 20,
        name: "Player 4",
        backgroundColor: getColorByKey("green"),
        icon: "heart",
        size: "l",
        xsElementsPerRow: 2,
        mdElementsPerRow: 3,
        lgElementsPerRow: 3,
      },
      {
        id: "player5",
        initialValue: 20,
        name: "Player 5",
        backgroundColor: getColorByKey("purple"),
        icon: "heart",
        size: "l",
        xsElementsPerRow: 2,
        mdElementsPerRow: 3,
        lgElementsPerRow: 3,
      },
    ],
  },
  {
    name: "6 Players",
    id: "life6",
    counters: [
      {
        id: "player1",
        initialValue: 20,
        name: "Player 1",
        backgroundColor: getColorByKey("red"),
        icon: "heart",
        size: "l",
        xsElementsPerRow: 2,
        mdElementsPerRow: 3,
        lgElementsPerRow: 3,
      },
      {
        id: "player2",
        initialValue: 20,
        name: "Player 2",
        backgroundColor: getColorByKey("blue"),
        icon: "heart",
        size: "l",
        xsElementsPerRow: 2,
        mdElementsPerRow: 3,
        lgElementsPerRow: 3,
      },
      {
        id: "player3",
        initialValue: 20,
        name: "Player 3",
        backgroundColor: getColorByKey("green"),
        icon: "heart",
        size: "l",
        xsElementsPerRow: 2,
        mdElementsPerRow: 3,
        lgElementsPerRow: 3,
      },
      {
        id: "player4",
        initialValue: 20,
        name: "Player 4",
        backgroundColor: getColorByKey("yellow"),
        icon: "heart",
        size: "l",
        xsElementsPerRow: 2,
        mdElementsPerRow: 3,
        lgElementsPerRow: 3,
      },
      {
        id: "player5",
        initialValue: 20,
        name: "Player 5",
        backgroundColor: getColorByKey("purple"),
        icon: "heart",
        size: "l",
        xsElementsPerRow: 2,
        mdElementsPerRow: 3,
        lgElementsPerRow: 3,
      },
      {
        id: "player6",
        initialValue: 20,
        name: "Player 6",
        backgroundColor: getColorByKey("orange"),
        icon: "heart",
        size: "l",
        xsElementsPerRow: 2,
        mdElementsPerRow: 3,
        lgElementsPerRow: 3,
      },
    ],
  },
];

export { layoutTemplates };
